### PR TITLE
DSMYSQL-1514 API Docs update to upgrade functionality for crossover

### PR DESCRIPTION
**Pull request by ayersek64**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
build me

**Comment by ayersek64** [comment]
@cyrichardson Yes, please merge this PR.

**Comment by cyrichardson** [comment]
build me

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 68 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-66e91fce2/docs/cloud-databases/v1/). valid for 14 days

**Pull request merged**
