### PR TITLE
Create HA with config group

### PR DESCRIPTION
**Pull request by riddhi89**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-6b251be11d/docs/cloud-databases/v1/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-4d8c241554/docs/cloud-databases/v1/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-1f50dc79ef/docs/cloud-databases/v1/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-a7bbe18a28/docs/cloud-databases/v1/). :bow:

**Comment by riddhi89** [comment]
@meker12 : updated:)

**Pull request merged**
