### PR TITLE
DSMYSQL-1438 Release Notes for 3.4.0

### PR DESCRIPTION
**Pull request by ayersek64**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 24 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-2ce9470df/docs/cloud-databases/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 25 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e07260663/docs/cloud-databases/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
@ayersek64 Preview looks good to me. Please let me know if you'd like for me to merge this, or you can merge. Thanks again!

**Comment by ayersek64** [comment]
@cyrichardson I do not have 'the power' to merge, but maybe that is because the default test is still pending

**Comment by cyrichardson** [comment]
@ayersek64 That "default" build no longer works. The "deconst-jenkins" one is the only one we review  for staging now.

Oh, and you are right about permissions. Would you like for me to merge? The staging preview LGTM.

**Comment by ayersek64** [comment]
@cyrichardson Yes, please merge this PR. Thank you for your quick review.

**Comment by catlook** [comment]
build/pub kicked off

**Comment by cyrichardson** [comment]
@ayersek64 Finally published thanks to a manual kick from @catlook. Automation was hung up. 
https://developer.rackspace.com/docs/cloud-databases/v1/release-notes/

**Pull request merged**
