### PR TITLE
Update/Add status maps

### PR DESCRIPTION
**Pull request by riddhi89**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-8dfa133399/docs/cloud-databases/v1/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-d95fb6c9b2/docs/cloud-databases/v1/developer-guide/). :bow:

**Comment by meker12** [comment]
@riddhi89   I submitted two pull requests to your fork to reformat the status descriptions in a table and minor edits for style.  When those updates look OK, you can merge them to your fork.  Then, we can merge this PR to master.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-ad1498a711/docs/cloud-databases/v1/developer-guide/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-81c0ff82a2/docs/cloud-databases/v1/developer-guide/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-219bb56235/docs/cloud-databases/v1/developer-guide/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-f8240e2800/docs/cloud-databases/v1/developer-guide/). :bow:

**Pull request merged**
