### PR TITLE
DSMYSQL-1000 Release Notes Last Updated January-28th-2016

### PR DESCRIPTION
**Pull request by ayersek64**
This PR is to add version 3 release notes with the intent to keep the release notes updated with each new release.
At a future date, additional PRs may be submitted to add additional release notes that have not been included.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by ayersek64** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by ayersek64** [comment]
build me

**Pull request merged**
