### PR TITLE
Add link to new CA cert in using-ssl.rst

### PR DESCRIPTION
**Pull request by RackerSCroce**
All instances created after March 1, 2016 will use a new Ssl certificate. This update will point customers to the right CA cert

This one is fairly urgent, so would like this pushed through quickly if possible

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-17c4598abb/docs/cloud-databases/v1/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-7bfb110b25/docs/cloud-databases/v1/developer-guide/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-04b8fd5f3f/docs/cloud-databases/v1/developer-guide/).

**Comment by meker12** [comment]
@RackerSCroce A few minor tweaks. Looks good!

**Pull request merged**
