### PR TITLE
DSMYSQL-1463 Release Notes for 3.6.0

### PR DESCRIPTION
**Pull request by ayersek64**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 49 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e0d297f8c/docs/cloud-databases/v1/). valid for 14 days

**Comment by ayersek64** [comment]
@catlook Who should I request review this PR to get it approved/merged?

**Comment by cyrichardson** [comment]
On it, @ayersek64 @catlook.

**Comment by cyrichardson** [comment]
@ayersek64 I see these release notes are dated 2/4 so I'm going to merge them. 

For next time, just post in the #docs Slack channel that you need a review/merge. All the Information Developers are watching there and will address your docs. So you don't need to depend on any one InfoDev person.

Thanks a ton for your docs contribution!

**Comment by catlook** [comment]
Kevin,

I’ve manually kicked of the publish-to-production pipeline.  In the past, this pipeline kicked off automatically when a PR merged.  For now, please notify us in #docs to make sure we get the change all the way to the published doc after it’s approved and merged!


-- Cat Lookabaugh, Information Developer IV
              rackspace
        Experience Services, Content Team
                    Cell: (210) 364-1060

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Comment by cyrichardson** [comment]
@ayersek64 @catlook Published at https://developer.rackspace.com/docs/cloud-databases/v1/release-notes/#v3-6-0-february-4-2020 

Thanks!

**Pull request merged**
