### PR TITLE
Update and correct trove client installation

### LINKED ISSUE #39: Trove Client Setup Incorrectly Labeled For OSX
https://developer.rackspace.com/docs/cloud-databases/v1/developer-guide/#install-the-trove-client

Section reads: 

> For Ubuntu, Debian, or OS X:
> 
> $ sudo apt-get install python2.7-dev
> 
> $ sudo pip install python-troveclient

apt-get is not available on OSX, homebrew is one of the more popular package managers for OS. See http://brew.sh/ for more info.

consider offering the following command for OSX, which will install python @ 2.7.11
>$ brew install python

### PR DESCRIPTION
**Pull request by meker12**
instructions. Fixes #39.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-57e4f6a977/docs/cloud-databases/v1/developer-guide/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-57e4f6a977/docs/cloud-databases/v1/developer-guide/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-729fe5d778/docs/cloud-databases/v1/developer-guide/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-b1c2833cbc/docs/cloud-databases/v1/developer-guide/)

**Comment by kylelaffoon** [comment]
This reads well and the table information with the issue is correct now. Nicely done @meker12 !

**Pull request merged**
