### PR TITLE
DSMYSQL-1445 Release Notes for 3.5.0

### PR DESCRIPTION
**Pull request by ayersek64**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@ayersek64 I believe the issue is with the build and not the content. I will keep you posted as others investigate.

**Comment by cyrichardson** [comment]
@ayersek64 Build is still failing. Do you have a deadline for publishing these release notes? (I've engaged docs toolchain folks.)

**Comment by ayersek64** [comment]
No hard deadline, but the release has already been deployed to production and getting release notes posted is a blocker to closing out the release in JIRA.
I would put this at a normal priority, not critical or major since it isn't blocking users.

**Comment by cyrichardson** [comment]
Thanks, @ayersek64. Not sure what is up... other repo builds are happening... just not docs-cloud-databases.... still working on it though.

**Comment by WilliamLoy** [comment]
Build me

**Comment by cyrichardson** [comment]
@ayersek64 We're hoping to get some dev help on Monday. I'll be on PTO, but @catlook and @WilliamLoy will be here to help. Thanks for your patience.

**Comment by ayersek64** [comment]
Ok, no worries. I know it will get resolved, so I'm good.

**Comment by catlook** [comment]
build me

**Comment by ayersek64** [comment]
An update/progress on getting this PR merged?

**Comment by catlook** [comment]
other PRs are finally building again...let me restart this one!

**Comment by catlook** [comment]
build me

**Comment by ayersek64** [comment]
Seems like CDB is the only project that still has issues?

Should I try closing this PR and resubmitting?

**Comment by catlook** [comment]
not yet... I'm trying an experiment.  I'm opening a new pr starting from the 9/25 commit.  If that builds successfully, I'll apply your changes and we can move on.  I don't think it's anything you did, but something is wonky.

**Comment by catlook** [comment]
I cannot get the simplest PR to build even starting with a successful commit back in March. I'm looking for more expert help.  Short of rebuilding the repo from scratch, I'm stumped.  Stand by.

**Pull request closed without merging**
