### PR TITLE
DSMYSQL-1513 Release Notes for 3.8.0

### PR DESCRIPTION
**Pull request by ayersek64**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by cyrichardson** [comment]
build me

**Comment by ayersek64** [comment]
@cyrichardson Wow, looks like I need an English writing refresher. <grin>
Yes, please merge this PR.

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 67 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bd601bb97/docs/cloud-databases/v1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 70 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-713270591/docs/cloud-databases/v1/). valid for 14 days

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 73 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-713270591/docs/cloud-databases/v1/). valid for 14 days

**Pull request merged**
