### PR TITLE
Netlify Setup

### PR DESCRIPTION
**Pull request by codebyravi**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 101 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-878cd07a2/docs/cloud-databases/v1/). valid for 14 days

**Comment by ayersek64** [comment]
The Nexus preview is missing 3.11.0 release notes and I'm not sure about other recent updates.

**Comment by rackernexus** [comment]
Build 103 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a3870dc70/docs/cloud-databases/v1/). valid for 14 days

**Comment by codebyravi** [comment]
Updated with the new release notes

**Review by ayersek64 — APPROVED** [review]
Nexus preview looks good.

**Pull request merged**
